# ──────────────────────────────────────────────────────────────────────────────
# HospEase - Guest Reservation Service Externalized Configuration
# ──────────────────────────────────────────────────────────────────────────────

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/guest_reservation_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

# SQL Init
spring.sql.init.mode=never

# JWT
app.jwt.secret=${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007}

# Feign
spring.cloud.openfeign.okhttp.enabled=true

# Fallback URLs
room-service.url=http://localhost:8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
