package com.cognizant.hospease.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;

@Slf4j
@Service
public class PdfGeneratorService {

    @Value("${report.storage.path}")
    private String folderPath;

    private final ObjectMapper objectMapper = new ObjectMapper();

    // ─── Scope colour map ────────────────────────────────────────────────────────

    private static final Map<String, Color> SCOPE_COLORS = Map.of(
            "OCCUPANCY",    new Color(0,   102, 204),
            "FINANCE",      new Color(0,   128,  0),
            "STAFF",        new Color(102,   0, 153),
            "HOUSEKEEPING", new Color(204, 102,   0),
            "SERVICES",     new Color(153,   0,   0),
            "GENERAL",      new Color(64,   64,  64)
    );

    private static final Map<String, String> SCOPE_LABELS = Map.of(
            "OCCUPANCY",    "ROOM OCCUPANCY REPORT",
            "FINANCE",      "FINANCIAL SUMMARY REPORT",
            "STAFF",        "STAFF ACTIVITY REPORT",
            "HOUSEKEEPING", "HOUSEKEEPING OPERATIONS REPORT",
            "SERVICES",     "SERVICE ORDERS REPORT",
            "GENERAL",      "GENERAL OPERATIONAL REPORT"
    );

    // ─── Public API ──────────────────────────────────────────────────────────────

    /**
     * Generates a scope-aware operational report PDF.
     * Called by ReportService.
     */
    public String generateReportPdf(String fileName, String reportTitle, String scope,
                                    String staffLabel, String contentSummary) throws IOException {
        ensureDirectory();
        String filePath = folderPath + File.separator + fileName;

        String scopeKey   = scope != null ? scope.toUpperCase() : "GENERAL";
        Color  scopeColor = SCOPE_COLORS.getOrDefault(scopeKey, new Color(64, 64, 64));
        String scopeLabel = SCOPE_LABELS.getOrDefault(scopeKey, "OPERATIONAL REPORT");

        Document document = new Document(PageSize.A4, 36, 36, 54, 36);
        try (FileOutputStream fos = new FileOutputStream(filePath)) {
            PdfWriter.getInstance(document, fos);
            document.open();

            addBrandingHeader(document, scopeColor);

            // Report title
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, scopeColor);
            Paragraph title = new Paragraph(reportTitle.toUpperCase(), titleFont);
            title.setSpacingAfter(6f);
            document.add(title);

            // Scope badge
            addScopeBadge(document, scopeKey, scopeColor);
            document.add(new Paragraph(" "));

            // Meta row
            addMetaRow(document,
                    "Run Date: " + now(),
                    "Generated By: " + (staffLabel != null ? staffLabel : "—"));

            addDivider(document);

            // Section heading
            document.add(sectionHeading(scopeLabel, scopeColor));
            document.add(new Paragraph(" "));

            // Content summary box
            if (contentSummary != null && !contentSummary.isBlank()) {
                addContentBox(document, contentSummary);
            }

            addFooter(document);
            document.close();
        }
        log.info("Report PDF generated: {}", filePath);
        return filePath;
    }

    /**
     * Generates a structured audit package PDF by parsing the aggregated JSON.
     * Called by AuditPackageService.
     */
    public String generateAuditPdf(String fileName, LocalDate periodStart,
                                   LocalDate periodEnd, String contentsJson) throws IOException {
        ensureDirectory();
        String filePath   = folderPath + File.separator + fileName;
        Color  auditColor = new Color(0, 51, 102);

        Document document = new Document(PageSize.A4, 36, 36, 54, 36);
        try (FileOutputStream fos = new FileOutputStream(filePath)) {
            PdfWriter.getInstance(document, fos);
            document.open();

            addBrandingHeader(document, auditColor);

            // Title
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, auditColor);
            Paragraph title = new Paragraph("AUDIT PACKAGE REPORT", titleFont);
            title.setSpacingAfter(6f);
            document.add(title);

            // Meta row
            String period = (periodStart != null ? periodStart : "N/A")
                    + "  →  " + (periodEnd != null ? periodEnd : "N/A");
            addMetaRow(document,
                    "Run Date: " + now(),
                    "Audit Period: " + period);

            addDivider(document);

            // Parse JSON and render sections
            if (contentsJson != null && !contentsJson.isBlank()) {
                try {
                    @SuppressWarnings("unchecked")
                    Map<String, Object> data = objectMapper.readValue(contentsJson, Map.class);
                    addAuditSections(document, data, auditColor);
                } catch (Exception e) {
                    log.warn("Could not parse audit JSON — displaying raw text: {}", e.getMessage());
                    addContentBox(document, contentsJson);
                }
            }

            addFooter(document);
            document.close();
        }
        log.info("Audit PDF generated: {}", filePath);
        return filePath;
    }

    /**
     * Legacy compatibility method — delegates to generateReportPdf with GENERAL scope.
     */
    public String generatePdf(String fileName, String reportTitle,
                               String parameters, String dataSummary) throws IOException {
        return generateReportPdf(fileName, reportTitle, "GENERAL", parameters, dataSummary);
    }

    // ─── Shared layout helpers ───────────────────────────────────────────────────

    private void ensureDirectory() {
        File dir = new File(folderPath);
        if (!dir.exists()) dir.mkdirs();
    }

    private void addBrandingHeader(Document doc, Color color) throws DocumentException {
        Font brandFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24, color);
        Paragraph brand = new Paragraph("HOSPEASE HOTEL GROUP", brandFont);
        brand.setAlignment(Element.ALIGN_LEFT);
        doc.add(brand);

        Font subFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.GRAY);
        doc.add(new Paragraph("Global Operations & Analytics Division", subFont));
        doc.add(new Paragraph(" "));
    }

    private void addScopeBadge(Document doc, String scope, Color color) throws DocumentException {
        PdfPTable t = new PdfPTable(1);
        t.setWidthPercentage(25);
        t.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell cell = new PdfPCell(new Phrase(scope,
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, Color.WHITE)));
        cell.setBackgroundColor(color);
        cell.setPadding(4);
        cell.setBorder(Rectangle.NO_BORDER);
        t.addCell(cell);
        doc.add(t);
    }

    private void addMetaRow(Document doc, String left, String right) throws DocumentException {
        PdfPTable t = new PdfPTable(2);
        t.setWidthPercentage(100);
        t.addCell(noBorderCell(left));
        t.addCell(noBorderCell(right));
        doc.add(t);
    }

    private void addDivider(Document doc) throws DocumentException {
        doc.add(new Paragraph(" "));
        doc.add(new Paragraph("________________________________________________________"));
        doc.add(new Paragraph(" "));
    }

    private Paragraph sectionHeading(String text, Color color) {
        return new Paragraph(text, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, color));
    }

    private void addContentBox(Document doc, String content) throws DocumentException {
        PdfPTable t = new PdfPTable(1);
        t.setWidthPercentage(100);
        t.setSpacingBefore(5f);
        PdfPCell cell = new PdfPCell(new Phrase(content,
                FontFactory.getFont(FontFactory.HELVETICA, 10)));
        cell.setPadding(10);
        cell.setBackgroundColor(new Color(245, 245, 245));
        t.addCell(cell);
        doc.add(t);
    }

    private void addFooter(Document doc) throws DocumentException {
        doc.add(new Paragraph(" "));
        Paragraph footer = new Paragraph(
                "© 2026 HospEase Group.  Confidential — Internal Use Only.",
                FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 8, Color.GRAY));
        footer.setAlignment(Element.ALIGN_CENTER);
        doc.add(footer);
    }

    // ─── Audit sections (text format) ────────────────────────────────────────────

    @SuppressWarnings("unchecked")
    private void addAuditSections(Document doc, Map<String, Object> data,
                                  Color color) throws DocumentException {

        Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, color);
        Font lineFont    = FontFactory.getFont(FontFactory.HELVETICA, 10);
        Font boldLine    = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10);

        // ── 1. ROOM OCCUPANCY ─────────────────────────────────────────────────
        Object roomsObj = data.get("rooms");
        if (roomsObj instanceof Map) {
            Map<String, Object> rooms = (Map<String, Object>) roomsObj;

            doc.add(textSectionTitle("1.  Room Occupancy", sectionFont));
            doc.add(textLine("Total Rooms",     valueOf(rooms, "total"),    lineFont));
            doc.add(textLine("Occupied Rooms",  valueOf(rooms, "occupied"), lineFont));

            Object total = rooms.get("total"), occupied = rooms.get("occupied");
            if (total instanceof Number && occupied instanceof Number) {
                long vacant = ((Number) total).longValue() - ((Number) occupied).longValue();
                doc.add(textLine("Vacant Rooms", String.valueOf(vacant), lineFont));
                if (((Number) total).longValue() > 0) {
                    double rate = (double) ((Number) occupied).longValue()
                            / ((Number) total).longValue() * 100;
                    doc.add(textLine("Occupancy Rate", String.format("%.1f%%", rate), boldLine));
                }
            }
            doc.add(new Paragraph(" "));
        }

        // ── 2. RESERVATIONS ───────────────────────────────────────────────────
        Object resObj = data.get("reservations");
        if (resObj instanceof Map) {
            Map<String, Object> res = (Map<String, Object>) resObj;
            doc.add(textSectionTitle("2.  Reservations", sectionFont));
            doc.add(textLine("Total Reservations", valueOf(res, "total"), lineFont));
            doc.add(new Paragraph(" "));
        }

        // ── 3. SERVICE ORDERS ─────────────────────────────────────────────────
        Object soObj = data.get("serviceOrders");
        if (soObj instanceof Map) {
            Map<String, Object> so = (Map<String, Object>) soObj;
            doc.add(textSectionTitle("3.  Service Orders", sectionFont));
            doc.add(textLine("Total Service Orders", valueOf(so, "total"), lineFont));
            doc.add(new Paragraph(" "));
        }

        // ── 4. FINANCE SUMMARY ────────────────────────────────────────────────
        Object finObj = data.get("finance");
        if (finObj instanceof Map) {
            Map<String, Object> fin = (Map<String, Object>) finObj;
            doc.add(textSectionTitle("4.  Finance Summary", sectionFont));
            doc.add(textLine("Paid Invoices",   valueOf(fin, "paid"),   lineFont));
            doc.add(textLine("Unpaid Invoices", valueOf(fin, "unpaid"), lineFont));
            Object rev = fin.get("revenue");
            doc.add(textLine("Total Revenue", rev != null ? "$" + rev : "$0.00", boldLine));
            doc.add(new Paragraph(" "));
        }

        // ── 5. REPORTS GENERATED ──────────────────────────────────────────────
        Object repObj = data.get("reports");
        if (repObj instanceof Map) {
            Map<String, Object> rep = (Map<String, Object>) repObj;
            doc.add(textSectionTitle("5.  Reports Generated", sectionFont));
            doc.add(textLine("Total Reports", valueOf(rep, "total"), lineFont));
            doc.add(new Paragraph(" "));
        }

        // ── 6. COMPLIANCE STATUS ──────────────────────────────────────────────
        String status      = data.getOrDefault("complianceStatus", "UNKNOWN").toString();
        Color  statusColor = "PASSED".equalsIgnoreCase(status)
                ? new Color(0, 128, 0) : new Color(200, 0, 0);

        doc.add(textSectionTitle("6.  Compliance Status", sectionFont));
        Paragraph statusLine = new Paragraph();
        statusLine.setIndentationLeft(20f);
        statusLine.add(new Chunk("Status  :  ", lineFont));
        statusLine.add(new Chunk(status,
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, statusColor)));
        doc.add(statusLine);
        doc.add(new Paragraph(" "));

        // ── 7. ADDITIONAL NOTES (optional) ────────────────────────────────────
        Object notes = data.get("userNotes");
        if (notes != null && !notes.toString().isBlank()) {
            doc.add(textSectionTitle("7.  Additional Notes", sectionFont));
            Paragraph notePara = new Paragraph(notes.toString(), lineFont);
            notePara.setIndentationLeft(20f);
            notePara.setSpacingBefore(2f);
            doc.add(notePara);
            doc.add(new Paragraph(" "));
        }
    }

    // ─── Text formatting helpers ──────────────────────────────────────────────────

    /** Underlined bold section title with spacing */
    private Paragraph textSectionTitle(String title, Font font) {
        Paragraph p = new Paragraph(title, font);
        p.setSpacingBefore(4f);
        p.setSpacingAfter(4f);
        return p;
    }

    /** Indented  "Label  :  Value"  line */
    private Paragraph textLine(String label, String value, Font valueFont) {
        Font labelFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.DARK_GRAY);
        Paragraph p = new Paragraph();
        p.setIndentationLeft(20f);
        p.add(new Chunk(String.format("%-28s:  ", label), labelFont));
        p.add(new Chunk(value, valueFont));
        return p;
    }

    private PdfPCell noBorderCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text,
                FontFactory.getFont(FontFactory.HELVETICA, 10)));
        cell.setBorder(Rectangle.NO_BORDER);
        return cell;
    }

    private String valueOf(Map<String, Object> map, String key) {
        Object v = map.get(key);
        if (v == null) return "N/A";
        String s = v.toString();
        return "-1".equals(s) ? "Unavailable" : s;
    }

    private String now() {
        return LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm"));
    }
}
